import { createHash } from "node:crypto";
import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { Client, InMemoryTransport } from "@modelcontextprotocol/client";
import { generateFromRun } from "@uig/cli/generate-from-run";
import { planFromUrl } from "@uig/cli/plan-from-url";
import type { PixsoDslClient } from "@uig/provider-pixso";
import { createProjectContextService } from "@uig/project-context";
import { afterEach, describe, expect, it } from "vitest";

import { createUigMcpServer } from "../src/server.js";
import { createProjectContextTools } from "../src/project-context-tools.js";
import { createUigTools } from "../src/tools.js";

const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const packPath = join(repoRoot, "design-system-packs", "sber-space-ui");
const adapterModulePath = join(repoRoot, "dist", "qwen-adapter.mjs");
const pixsoUrl =
  "https://pixso.net/app/design/WSLukjrKancvZG0zbaMnyA?item-id=4:314";
const fixedNow = () => new Date("2026-07-27T00:00:00.000Z");

describe("direct service and MCP adapter parity", () => {
  const roots: string[] = [];

  afterEach(async () => {
    await Promise.all(
      roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
    );
  });

  it("stores identical plans and generated bytes for Pixso 4:314", async () => {
    const [directWorkspace, mcpWorkspace] = await Promise.all([
      temporaryWorkspace(roots, "uig-direct-parity-"),
      temporaryWorkspace(roots, "uig-mcp-parity-"),
    ]);
    const rawDsl = await readFile(
      join(repoRoot, "fixtures", "pixso", "modal-4-314", "source.json"),
    );
    const directRun = await planFromUrl({
      url: pixsoUrl,
      designSystemPackPath: packPath,
      workspaceDir: directWorkspace,
      pixsoClient: staticPixsoClient(rawDsl),
      now: fixedNow,
    });
    const directGenerated = await generateFromRun({
      runId: directRun.runId,
      workspaceDir: directWorkspace,
      explicitPackPath: packPath,
    });

    const tools = createUigTools({
      workspaceDir: mcpWorkspace,
      extensionRoot: repoRoot,
      adapterModulePath,
      token: "parity-test-token",
      now: fixedNow,
      createPixsoClient: () => staticPixsoClient(rawDsl),
      planFromUrl,
      generateFromRun,
    });
    const projectContextTools = createProjectContextTools(
      createProjectContextService({
        workspaceDir: mcpWorkspace,
        extensionRoot: repoRoot,
      }),
    );
    const server = createUigMcpServer({
      tools: {
        ...tools,
        ...projectContextTools,
        prepareBuild: async () => ({
          schema: "uig-qwen-prepare-build-result/v1",
        }),
        recordImplementation: async () => ({
          schema: "uig-qwen-record-implementation-result/v1",
        }),
        recordCodeReview: async () => ({
          schema: "uig-qwen-record-code-review-result/v1",
        }),
        recordBrowserReview: async () => ({
          schema: "uig-qwen-record-browser-review-result/v1",
        }),
      },
    });
    const [clientTransport, serverTransport] =
      InMemoryTransport.createLinkedPair();
    const client = new Client({
      name: "uig-parity-test",
      version: "0.1.0",
    });
    await server.connect(serverTransport);
    await client.connect(clientTransport);
    const planned = await client.callTool({
      name: "uig_plan",
      arguments: {
        url: pixsoUrl,
        designSystem: "sber-space-ui",
      },
    });
    const plannedResult = planned.structuredContent as {
      runId: string;
      target: unknown;
      summary: unknown;
    };
    const generated = await client.callTool({
      name: "uig_generate",
      arguments: {
        runId: plannedResult.runId,
      },
    });
    await client.close();
    await server.close();

    expect(plannedResult.runId).toBe(directRun.runId);
    expect(generated.structuredContent).toMatchObject({
      schema: "uig-qwen-generate-result/v1",
      status: directGenerated.status,
      runId: directRun.runId,
    });
    const directRunDir = join(directWorkspace, ".uig", "runs", directRun.runId);
    const mcpRunDir = join(mcpWorkspace, ".uig", "runs", directRun.runId);
    const [directPlan, mcpPlan] = await Promise.all([
      readFile(join(directRunDir, directRun.artifacts.resolutionPlan), "utf8"),
      readFile(join(mcpRunDir, directRun.artifacts.resolutionPlan), "utf8"),
    ]);
    expect(mcpPlan).toBe(directPlan);
    expect(await fileHashMap(join(mcpRunDir, "generated"))).toEqual(
      await fileHashMap(join(directRunDir, "generated")),
    );

    const serialized = JSON.stringify({
      planned: planned.structuredContent,
      generated: generated.structuredContent,
    });
    expect(serialized).not.toContain('"dsl"');
    expect(serialized).not.toContain("design-ir/v2");
    expect(serialized).not.toContain("ui-manifest/v2");
    expect(serialized).not.toContain("resolution-plan/v2");
    expect(serialized).not.toContain("parity-test-token");
  }, 20_000);
});

function staticPixsoClient(bytes: Uint8Array): PixsoDslClient {
  return {
    async getNodeDsl() {
      return bytes;
    },
  };
}

async function temporaryWorkspace(
  roots: string[],
  prefix: string,
): Promise<string> {
  const workspace = await mkdtemp(join(tmpdir(), prefix));
  roots.push(workspace);
  return workspace;
}

async function fileHashMap(directory: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  await visit(directory, directory, result);
  return result;
}

async function visit(
  root: string,
  directory: string,
  result: Record<string, string>,
): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      await visit(root, path, result);
    } else {
      const relative = path.slice(root.length + 1).replaceAll("\\", "/");
      result[relative] = createHash("sha256")
        .update(await readFile(path))
        .digest("hex");
    }
  }
}
